### ISSUE TITLE
Question: building the refactored meterpreter project

### ISSUE THREAD

**Issue by pussinboots1992** [scrt/avcleaner#3] opened 2020-06-27 22:01 UTC
Thanks again for the awesome blog post and publishing this ! Great work !

I do have a few questions though. I have gone ahead and ran the transformations on many .c files in the metasploit-payloads project...However I am no longer able to build. For example, I get the following errors:

```
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I..\..\source\ReflectiveDLLInjection\common /I..\..\source\ReflectiveDLLInjection\inject\src /I..\..\source\ReflectiveDLLInjection\dll\sr
  c /I..\..\deps\openssl\include /Zi /nologo /W3 /WX /O1 /Ob1 /Os /Oy- /D WIN32 /D NDEBUG /D _LIB /D _USING_V110_SDK71_ /D _UNICODE /D UNICODE /GF /Gm- /EHsc /MT /GS- /Gy- /fp:precise /Zc:wchar_t /Zc:forScope
  /Fo"Release\Win32\\" /Fd"Release\Win32\vc120.pdb" /Gd /TC /analyze- /errorReport:queue ..\..\source\DelayLoadMetSrv\DelayLoadMetSrv.c ..\..\source\ReflectiveDLLInjection\inject\src\GetProcAddressR.c ..\..\so
  urce\ReflectiveDLLInjection\inject\src\LoadLibraryR.c ..\..\source\ReflectiveDLLInjection\dll\src\ReflectiveLoader.c
  DelayLoadMetSrv.c
..\..\source\DelayLoadMetSrv\DelayLoadMetSrv.c(60): error C2220: warning treated as error - no 'object' file generated [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ReflectiveDLLInjection\Reflec
tiveDLLInjection.vcxproj]
..\..\source\DelayLoadMetSrv\DelayLoadMetSrv.c(60): warning C4133: 'function' : incompatible types - from 'TCHAR [11]' to 'const char *' [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ReflectiveD
LLInjection\ReflectiveDLLInjection.vcxproj]
..\..\source\DelayLoadMetSrv\DelayLoadMetSrv.c(67): warning C4133: 'function' : incompatible types - from 'TCHAR [11]' to 'const char *' [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ReflectiveD
LLInjection\ReflectiveDLLInjection.vcxproj]
  GetProcAddressR.c
  LoadLibraryR.c
  ReflectiveLoader.c
  Generating Code...
Done Building Project "C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ReflectiveDLLInjection\ReflectiveDLLInjection.vcxproj" (default targets) -- FAILED.
```
This is what the refactored file looks like:
```
//===============================================================================================//
// Copyright (c) 2009, Stephen Fewer of Harmony Security (www.harmonysecurity.com)
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without modification, are permitted 
// provided that the following conditions are met:
// 
//     * Redistributions of source code must retain the above copyright notice, this list of 
// conditions and the following disclaimer.
// 
//     * Redistributions in binary form must reproduce the above copyright notice, this list of 
// conditions and the following disclaimer in the documentation and/or other materials provided 
// with the distribution.
// 
//     * Neither the name of Harmony Security nor the names of its contributors may be used to
// endorse or promote products derived from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR 
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
// POSSIBILITY OF SUCH DAMAGE.
//===============================================================================================//
#include "DelayLoadMetSrv.h"
#include "GetProcAddressR.h"

// The handle to the injected metsrv.dll, needed for delay loading...
HMODULE hMetSrv = NULL; 

// All server extensions must support delay loading of metsrv.dll because this dll can be injected
// via reflective dll injection, as such normal calls to LoadLibrary/GetModuleHandle/GetProcAddress
// to resolve exports in metsrv.dll will not work as metsrv.dll will be 'invisible' to the native 
// windows kernel32 api's. Theirfore we delay load metsrv.dll and intercept loading and resolving of
// its exports and resolve them using our own GetProcAddressR() function.
// 
// To enable all of this in a new extnesion:
// 1. Add metsrv.dll to the DELAYLOAD option in the projects properties (Configuration->Linker->Input).
// 2. Add in the include file #include "DelayLoadMetSrv.h".
// 3. Add the macro "EnableDelayLoadMetSrv();" after all your includes.
// 4. Add the line "hMetSrv = remote->hMetSrv;" in your InitServerExtension() function.

//===============================================================================================//




FARPROC WINAPI delayHook( unsigned dliNotify, PDelayLoadInfo pdli )
{
	
	TCHAR hid_metsrv_8An2Apu2Kv1U[] = {'m','e','t','s','r','v','.','d','l','l',0};
switch( dliNotify )
	{
		case dliNotePreLoadLibrary:
			// If we are trying to delay load metsrv.dll we can just return the
			// HMODULE of the injected metsrv library (set in InitServerExtension).
			if( strcmp( pdli->szDll, hid_metsrv_8An2Apu2Kv1U ) == 0 )
				return (FARPROC)hMetSrv;
			break;
		case dliNotePreGetProcAddress:
			// If we are trying to get the address of an exported function in the
			// metsrv.dll we must use GetProcAddressR() in case the metsrv was loaded
			// via reflective dll injection
			if( strcmp( pdli->szDll, "metsrv.dll" ) == 0 )
				return GetProcAddressR( pdli->hmodCur, pdli->dlp.szProcName );
			break;
		default:
			return NULL;
	}

	return NULL;
}
//===============================================================================================//
```

Although it's kind of odd that in one case I got:

**`if( strcmp( pdli->szDll, hid_metsrv_8An2Apu2Kv1U ) == 0 )`**

and in another case:

**`if( strcmp( pdli->szDll, "metsrv.dll" ) == 0 )`**

Can you give me some insight into the challenges you faced with using this approach ? Was it a smooth process or was there a lot of manual adjustments required to make it build successfully after refactoring the source files using libclang ?

**Comment by plowsec** [comment] 2020-06-28 20:34
In this case, refactoring introduces warnings. And since the visual studio projects of Meterpreter are configured to admit no warnings, the build fails. So you can either improve the obfuscator to correctly handle cases where a constant string is expected (I would just add a cast) or you can decide that you don't care about those warnings and update the projects configurations. I think it's in "Project Configuration -- C/C++ -- Treat warnings as error".

Other than that, I don't understand why the second "metsrv.dll" was left out, I will link into it because that's never happened before.

**Comment by pussinboots1992** [comment] 2020-06-29 05:42
@plowsec, I remove all the /WX flags in Visual Studio from all projects in the solution however there are still compiler errors:

**"C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ext_server_mimikatz.vcxproj" (Rebuild target) (12:2) ->
  ..\..\source\extensions\mimikatz\main.cpp(95): error C2440: 'initializing' : cannot convert from 'TCHAR [24]' to 'LPCSTR' [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ext_
server_mimikatz.vcxproj]
  ..\..\source\extensions\mimikatz\main.cpp(133): error C2664: 'errno_t strncpy_s(char *,rsize_t,const char *,rsize_t)' : cannot convert argument 3 from 'TCHAR [9]' to 'const char *' [C:\Users\puss\Dev\msf-
obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ext_server_mimikatz.vcxproj]
  ..\..\source\extensions\mimikatz\mimikatz.cpp(153): error C2065: 'hid________OZoGJF2b256D' : undeclared identifier [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ext_server_
mimikatz.vcxproj]**

```
..\..\source\extensions\mimikatz\modules\mod_system.cpp(135): error C2065: 'hid_n_t_d__GhUcy0bsQvJz' : undeclared identifier [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\e
xt_server_mimikatz.vcxproj]
  ..\..\source\extensions\mimikatz\modules\mod_system.cpp(135): error C2059: syntax error : ')' [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ext_server_mimikatz.vcxproj]
  ..\..\source\extensions\mimikatz\modules\mod_system.cpp(137): error C2144: syntax error : 'DWORD' should be preceded by '}' [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ex
t_server_mimikatz.vcxproj]
  ..\..\source\extensions\mimikatz\modules\mod_system.cpp(137): error C2144: syntax error : 'DWORD' should be preceded by ';' [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ex
t_server_mimikatz.vcxproj]
  ..\..\source\extensions\mimikatz\modules\mod_system.cpp(162): error C2059: syntax error : 'return' [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ext_server_mimikatz.vcxproj
]
  ..\..\source\extensions\mimikatz\modules\mod_system.cpp(163): error C2059: syntax error : '}' [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ext_server_mimikatz.vcxproj]
  ..\..\source\extensions\mimikatz\modules\mod_system.cpp(163): error C2143: syntax error : missing ';' before '}' [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ext_server_mi
mikatz.vcxproj]
  ..\..\source\extensions\mimikatz\modules\mod_system.cpp(166): error C2143: syntax error : missing ';' before '{' [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimikatz\ext_server_mi
mikatz.vcxproj]
  ..\..\source\extensions\mimikatz\modules\mod_system.cpp(166): error C2447: '{' : missing function header (old-style formal list?) [C:\Users\puss\Dev\msf-obfuscated\c\meterpreter\workspace\ext_server_mimik
atz\ext_server_mimikatz.vcxproj]
  ..\..\source\extensions\mimikatz\modules\mod_text.cpp(12): error C2664: 'FARPROC GetProcAddress(HMODULE,LPCSTR)' : cannot convert argument 2 from 'TCHAR [14]' to 'LPCSTR' [C:\Users\puss\Dev\msf-obfuscated
\c\meterpreter\workspace\ext_server_mimikatz\ext_server_mimikatz.vcxproj]
  ..\..\source\extensions\mimikatz\modules\mod_text.cpp(17): error C2664: 'FARPROC GetProcAddress(HMODULE,LPCSTR)' : cannot convert argument 2 from 'TCHAR [21]' to 'LPCSTR' [C:\Users\puss\Dev\msf-obfuscated
\c\meterpreter\workspace\ext_server_mimikatz\ext_server_mimikatz.vcxproj]
```

Like you said, some could be solved by casting but could you possibly make some suggestions as to which file you chose to run the transformations on ? You mentioned in the blog post that you were only able to refactor half of the code base, is this what I am encountering here ? I also notices that the following, when running the transformation on this sample, it seems to ignore the strings which have less than 6 characters :

```
int main() {
    
char *customcommands[] = 
    {
        "foo",
        "bar",
        "foofoofoo",
        "barbarbar"
    };

    return 0;
}
```
Output:
```
int main() {
    

	TCHAR hid_foofoo_vwZZB4yjkuxL[] = {'f','o','o','f','o','o','f','o','o',0};

	TCHAR hid_barbar_TQPbUT0R9na8[] = {'b','a','r','b','a','r','b','a','r',0};
char *customcommands[] = 
    {
        "foo",
        "bar",
        hid_foofoo_vwZZB4yjkuxL,
        hid_barbar_TQPbUT0R9na8
    };

    return 0;
}
```

**Comment by plowsec** [comment] 2020-06-29 11:38
Yes I chose to ignore string that comprise less than 6 characters, you can change that as you will.

I run the obfuscator on the whole meterpreter codebase, but while the AST fails to build for a large part of the project, it does not introduce syntax errors. BUT the code you see in this repo was rewritten from scratch for the purpose of this blog post. Our private version comprises 8k+ lines of code and was simply too complicated to explain in a blog post.

That does not mean I won't fix the issues you're encountering, but give me a week or two :P

(and I accept pull requests)

**Comment by pussinboots1992** [comment] 2020-07-01 10:23
@plowsec , cool thanks for looking into it.

You ignore string with less than 6 chars because AV couldn't get a solid signature on so few chars ?

 Do not count on a pull request from my side soon :-) I know nothing about Clang or LLVM and this is kind of intimidating:

` "...Its documentation being the source code, we recommend allocating a week or two to ingest it as a whole..."`

PS: Are the winapi headers really necessary for the tooling to work ? I had some files which complained but were obfuscated despite the errors...

**Comment by plowsec** [comment] 2020-07-09 18:58
> Although it's kind of odd that in one case I got:
> 
> **`if( strcmp( pdli->szDll, hid_metsrv_8An2Apu2Kv1U ) == 0 )`**
> 
> and in another case:
> 
> **`if( strcmp( pdli->szDll, "metsrv.dll" ) == 0 )`**

I tried to reproduce the issue by obfuscating DelayLoadMetSrv.c (which does not exist anymore on the latest metasploit-payloads), but both strings are successfully obfuscated.

As for your second issue, I think you're trying to obfuscate this old version of mimikatz. It could be an interesting bench test but I'm afraid I would waste my time fixing issues that are not triggered anywhere else.

> PS: Are the winapi headers really necessary for the tooling to work ? I had some files which complained but were obfuscated despite the errors...

No there are no necessary if your project does not depend on them. Treat this obfuscator as a compiler frontend, if you need these headers to build your project, then the obfuscator needs them as well.

**Closed** 2020-09-18 13:36 UTC
